<?php
/**
 * Language Translations (English/French)
 */

$translations = [
    'en' => [
        'dashboard' => 'Dashboard',
        'dashboard_overview' => 'Dashboard Overview',
        'inventory' => 'Inventory',
        'pos' => 'Point of Sale',
        'suppliers' => 'Suppliers',
        'reports' => 'Reports',
        'users' => 'Users',
        'settings' => 'Settings',
        'customers' => 'Customers',
        'expenses' => 'Expenses',
        'prescriptions' => 'Prescriptions',
        'audit_logs' => 'Audit Logs',
        'logout' => 'Logout',
        'welcome' => 'Welcome Back',
        'today_sales' => "Today's Sales",
        'gross_sales' => 'Gross Sales',
        'tax_profit_today' => 'Tax Profit (Today)',
        'low_stock' => 'Low Stock Alert',
        'low_stock_alerts' => 'Low Stock Alerts',
        'expiring_soon' => 'Expiring Soon',
        'total_medicines' => 'Total Medicines',
        'recent_sales' => 'Recent Sales',
        'sales_analytics' => 'Sales Analytics',
        'medicine_name' => 'Medicine Name',
        'generic_name' => 'Generic Name',
        'category' => 'Category',
        'price' => 'Price',
        'stock' => 'Stock',
        'expiry' => 'Expiry',
        'actions' => 'Actions',
        'confirm_sale' => 'Confirm Sale',
        'total' => 'Total',
        'add_medicine' => 'Add New Medicine',
        'medicine_inventory' => 'Medicine Inventory',
        'payment_method' => 'Payment Method',
        'grand_total' => 'Grand Total',
        'explore' => 'Explore',
        'my_orders' => 'My Orders',
        'pending_sales' => 'Pending Sales',
        'new_sale' => 'New Sale',
        'export' => 'Export',
        'this_week' => 'This week',
        'medicine' => 'Medicine',
        'in_stock' => 'In Stock',
        'action' => 'Action',
        'expiry_date' => 'Expiry Date',
        'status' => 'Status',
        'restock' => 'Restock',
        'days_left' => 'days left',
        'view_all' => 'View All',
        'walk_in_customer' => 'Walk-in Customer',
        'no_recent_sales' => 'No recent sales found.',
        'current_order' => 'Current Order',
        'cart_empty' => 'Cart is empty',
        'subtotal' => 'Subtotal',
        'tax' => 'Tax',
        'select_customer' => 'Select or Enter Customer',
        'cash' => 'Cash',
        'card' => 'Card',
        'mobile_money' => 'Mobile Money',
        'send_to_cashier' => 'Send to Cashier',
        'add' => 'Add',
        'no_medicines_stock' => 'No medicines available in stock.',
        'no_medicines_found' => 'No medicines found.',
        'pharmacy' => 'Pharmacy',
        'supplier' => 'Supplier',
        'browse_drugs' => 'Browse Drugs by Pharmacy',
        'select_local_pharma' => 'Please select a local pharmacy to view their available medicine inventory.',
        'view_inventory' => 'View Inventory'
    ],
    'fr' => [
        'dashboard' => 'Tableau de bord',
        'dashboard_overview' => 'Aperçu du Tableau de bord',
        'inventory' => 'Inventaire',
        'pos' => 'Point de vente',
        'suppliers' => 'Fournisseurs',
        'reports' => 'Rapports',
        'users' => 'Utilisateurs',
        'settings' => 'Paramètres',
        'customers' => 'Clients',
        'expenses' => 'Dépenses',
        'prescriptions' => 'Ordonnances',
        'audit_logs' => "Journaux d'Audit",
        'logout' => 'Déconnexion',
        'welcome' => 'Bienvenue',
        'today_sales' => "Ventes d'aujourd'hui",
        'gross_sales' => 'Ventes Brutes',
        'tax_profit_today' => 'Bénéfice (Aujourd\'hui)',
        'low_stock' => 'Alerte stock bas',
        'low_stock_alerts' => 'Alertes de Stock Bas',
        'expiring_soon' => 'Expire bientôt',
        'total_medicines' => 'Total des médicaments',
        'recent_sales' => 'Ventes récentes',
        'sales_analytics' => 'Analyses des Ventes',
        'medicine_name' => 'Nom du médicament',
        'generic_name' => 'Nom générique',
        'category' => 'Catégories',
        'price' => 'Prix',
        'stock' => 'Stock',
        'expiry' => 'Expiration',
        'actions' => 'Actions',
        'confirm_sale' => 'Confirmer la vente',
        'total' => 'Total',
        'add_medicine' => 'Ajouter un nouveau médicament',
        'medicine_inventory' => 'Inventaire des médicaments',
        'payment_method' => 'Mode de paiement',
        'grand_total' => 'Total général',
        'explore' => 'Explorer',
        'my_orders' => 'Mes Commandes',
        'pending_sales' => 'Ventes en Attente',
        'new_sale' => 'Nouvelle Vente',
        'export' => 'Exporter',
        'this_week' => 'Cette semaine',
        'medicine' => 'Médicament',
        'in_stock' => 'En Stock',
        'action' => 'Action',
        'expiry_date' => 'Date d\'Expiration',
        'status' => 'Statut',
        'restock' => 'Réapprovisionner',
        'days_left' => 'jours restants',
        'view_all' => 'Voir Tout',
        'walk_in_customer' => 'Client de Passage',
        'no_recent_sales' => 'Aucune vente récente trouvée.',
        'current_order' => 'Commande Actuelle',
        'cart_empty' => 'Le panier est vide',
        'subtotal' => 'Sous-total',
        'tax' => 'Taxe',
        'select_customer' => 'Sélectionner ou Entrer Client',
        'cash' => 'Espèces',
        'card' => 'Carte',
        'mobile_money' => 'Argent Mobile',
        'send_to_cashier' => 'Envoyer au Caissier',
        'add' => 'Ajouter',
        'no_medicines_stock' => 'Aucun médicament disponible en stock.',
        'no_medicines_found' => 'Aucun médicament trouvé.',
        'pharmacy' => 'Pharmacie',
        'supplier' => 'Fournisseur',
        'browse_drugs' => 'Parcourir les Médicaments par Pharmacie',
        'select_local_pharma' => 'Veuillez sélectionner une pharmacie locale pour voir l\'inventaire.',
        'view_inventory' => 'Voir l\'Inventaire'
    ]
];


/**
 * Get translation for a key
 */
function __($key) {
    global $translations;
    $lang = $_SESSION['lang'] ?? 'en';
    return $translations[$lang][$key] ?? $key;
}
